In [52]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [53]:
df=pd.read_csv("customer_shopping_behavior.csv")

In [54]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [55]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [56]:
df["Review Rating"]=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [57]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [58]:
df.columns=df.columns.str.lower()

In [59]:
df.columns=df.columns.str.replace(' ','_')

In [60]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

Create New age column

In [61]:
labels=['Young Adult','Adult','Middle-aged','Senior'] 
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [62]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

#create column purchase_frequency_days

In [63]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-aged

In [64]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-weekly':14, 
    'Annually':365, 
    'Every 3 Month':90, 
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [65]:
df[['frequency_of_purchases','purchase_frequency_days']].head()

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                     14.0
1            Fortnightly                     14.0
2                 Weekly                      7.0
3                 Weekly                      7.0
4               Annually                    365.0

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount_(usd)    3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  promo_code_used          3900 non-null   object
 15  previous_purchases       3900 non-null   int64
 16  payment_method           3900 non-null   object
 17  frequency_of_purchases   3900 non-null   object
 18  age_group                3900 non-null   category
 19  purchase_frequency_days  2769 non-null   float64
dtypes: category(1), float64(2), int64(4), object(13)
memory usage: 583.0+ KB

In [67]:
(df[['discount_applied','promo_code_used']]).all()

discount_applied    True
promo_code_used     True
dtype: bool

In [68]:
df=df.drop('promo_code_used',axis=1)

In [ ]:
pip install mysql-connector-python

In [ ]:

pip install sqlalchemy

In [ ]:
from sqlalchemy import create_engine

In [ ]:
from sqlalchemy import create_engine
import urllib.parse

# ୟୁଜର୍ ଏବଂ ପାସୱାର୍ଡ
user = "root"
password = "Ashirbad@6372"

# '@' ଚିହ୍ନକୁ ସୁରକ୍ଷିତ ଭାବେ URL ରେ ବ୍ୟବହାର କରିବା ପାଇଁ Encode କରାଗଲା
safe_password = urllib.parse.quote_plus(password)

# Engine ତିଆରି କରନ୍ତୁ
engine = create_engine(f"mysql+mysqlconnector://{user}:{safe_password}@localhost/customer_behavior")

# ଏବେ ଡାଟା ସେଭ୍ କରନ୍ତୁ
df.to_sql(
    name='customer_data',
    con=engine,
    if_exists='replace',
    index=False
)

In [ ]:
df

In [ ]:
from sqlalchemy import create_engine
import urllib.parse

user = "root"
password = "Ashirbad@6372"
safe_password = urllib.parse.quote_plus(password)

# Engine ତିଆରି କଲେ
engine = create_engine(f"mysql+mysqlconnector://{user}:{safe_password}@localhost/customer_behavior")

# କନେକ୍ସନ୍ ଚେକ୍ କରିବା ପାଇଁ ଟେଷ୍ଟ କୋଡ୍
try:
    # ଡାଟାବେସ୍ ସହ କନେକ୍ଟ କରିବାକୁ ଚେଷ୍ଟା କରାଗଲା
    with engine.connect() as connection:
        print("✅ Success: Python successfully connected to MySQL!")
except Exception as e:
    print("❌ Connection Failed!")
    print("Error Details:", e)